import AppKit

/// Decides whether a pasteboard change should be stored at all.
///
/// Skips content explicitly marked transient/concealed (e.g. by password
/// managers), clips coming from known password-manager apps, and anything
/// larger than the configured cap.
enum PrivacyFilter {
    /// Pasteboard types apps use to opt out of clipboard history.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Bundle identifiers ignored by default.
    private static let ignoredBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
    ]

    static let maxItemBytes = 50 * 1024 * 1024

    static func shouldStore(_ pasteboard: NSPasteboard) -> Bool {
        if let types = pasteboard.types,
           types.contains(where: { excludedTypes.contains($0.rawValue) }) {
            return false
        }

        if let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ignoredBundleIDs.contains(bundleID) {
            return false
        }

        return true
    }
}
